[package]
name = "artlr_syntax"
version = "0.1.0"
authors = ["Roberto Pintos López <roberto.pintos.lopez@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
artlr_lex = "0.1.1"
